const sagaActionsType ={
    LOGIN_SAGA_ACTIONS:"LOGIN_SAGA_ACTIONS",
    COUNTER_INCREMENT:"COUNTER_INCREMENT",
    COUNTER_DECREMENT:"COUNTER_DECREMENT",
    COUNTER_ADD_BY_NUMBER : "COUNTER_ADD_BY_NUMBER"
}

export default sagaActionsType;